using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Zonit.Messaging.Events.SourceGenerators;

/// <summary>
/// Source Generator kt�ry automatycznie generuje rejestracj� handler�w event�w dla AOT/Trimming.
/// Skanuje projekt w poszukiwaniu klas implementuj�cych IEventHandler&lt;T&gt; i generuje:
/// 1. Extension method AddEventHandlers() dla automatycznej rejestracji wszystkich handler�w
/// 2. AOT-safe subscription bez reflection
/// </summary>
[Generator]
public class EventHandlerGenerator : IIncrementalGenerator
{
    private const string EventHandlerInterfaceName = "IEventHandler";
    private const string EventHandlerNamespace = "Zonit.Messaging.Events";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Znajd� wszystkie klasy dziedzicz�ce po EventBase<T>
        var handlerClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateHandlerClass(node),
                transform: static (ctx, _) => GetHandlerInfo(ctx))
            .Where(static info => info is not null);

        // Zbierz wszystkie handlery i wygeneruj kod
        var compilation = context.CompilationProvider.Combine(handlerClasses.Collect());

        context.RegisterSourceOutput(compilation, static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsCandidateHandlerClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl
               && classDecl.BaseList is not null
               && classDecl.BaseList.Types.Any();
    }

    private static EventHandlerInfo? GetHandlerInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);

        if (symbol is not INamedTypeSymbol classSymbol)
            return null;

        // Sprawd� czy klasa jest abstract lub static
        if (classSymbol.IsAbstract || classSymbol.IsStatic)
            return null;

        // Check for IEventHandler<T> interface (new API only)
        // Legacy EventBase<T> uses different registration system and should not be detected here
        foreach (var iface in classSymbol.AllInterfaces)
        {
            if (iface.IsGenericType
                && iface.Name == EventHandlerInterfaceName
                && iface.ContainingNamespace?.ToDisplayString() == EventHandlerNamespace
                && iface.TypeArguments.Length == 1)
            {
                var eventType = iface.TypeArguments[0];

                return new EventHandlerInfo(
                    HandlerFullName: classSymbol.ToDisplayString(),
                    HandlerName: classSymbol.Name,
                    EventFullName: eventType.ToDisplayString(),
                    EventName: eventType.Name,
                    Namespace: classSymbol.ContainingNamespace?.ToDisplayString() ?? "Global"
                );
            }
        }

        return null;
    }

    private static void Execute(Compilation compilation, ImmutableArray<EventHandlerInfo?> handlers, SourceProductionContext context)
    {
        var validHandlers = handlers
            .Where(h => h is not null)
            .Cast<EventHandlerInfo>()
            .Distinct()
            .ToList();

        if (validHandlers.Count == 0)
            return;

        var assemblyName = compilation.AssemblyName ?? "Unknown";
        var safeAssemblyName = assemblyName.Replace(".", "_").Replace("-", "_");

        var source = GenerateRegistration(validHandlers, safeAssemblyName);
        context.AddSource("EventHandlerRegistration.g.cs", source);
    }

    private static string GenerateRegistration(List<EventHandlerInfo> handlers, string safeAssemblyName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Zonit.Messaging.Events;");
        sb.AppendLine("using Zonit.Messaging.Events.Hosting;");
        sb.AppendLine();
        sb.AppendLine("namespace Zonit.Messaging.Events.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated event handler registrations.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"internal static class EventHandlerRegistrations_{safeAssemblyName}");
        sb.AppendLine("{");
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        EventSegmentRegistry.Register(RegisterServices);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    internal static void RegisterServices(IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var handler in handlers)
        {
            sb.AppendLine($"        // Handler: {handler.HandlerName} for event: {handler.EventName}");
            sb.AppendLine($"        services.TryAddScoped<{handler.HandlerFullName}>();");
            // Multiple handlers can exist per event - use TryAddEnumerable with concrete impl type
            // so GetServices<IEventHandler<T>>() returns all of them.
            sb.AppendLine($"        services.TryAddEnumerable(ServiceDescriptor.Scoped<IEventHandler<{handler.EventFullName}>, {handler.HandlerFullName}>(static sp => sp.GetRequiredService<{handler.HandlerFullName}>()));");
            sb.AppendLine($"        services.TryAddEnumerable(ServiceDescriptor.Singleton<EventHandlerRegistration>(new EventHandlerRegistration<{handler.EventFullName}>()));");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private record EventHandlerInfo(
        string HandlerFullName,
        string HandlerName,
        string EventFullName,
        string EventName,
        string Namespace
    );
}
