using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Zonit.Messaging.Tasks.SourceGenerators;

/// <summary>
/// Source Generator który automatycznie generuje rejestracjê handlerów zadañ dla AOT/Trimming.
/// Skanuje projekt w poszukiwaniu klas dziedzicz¹cych po TaskBase&lt;T&gt; i generuje:
/// 1. Extension method AddTaskHandlers() dla automatycznej rejestracji wszystkich handlerów
/// 2. AOT-safe subscription bez reflection
/// </summary>
[Generator]
public class TaskHandlerGenerator : IIncrementalGenerator
{
    private const string TaskBaseClassName = "TaskBase";
    private const string TaskBaseNamespace = "Zonit.Services.EventMessage";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // ZnajdŸ wszystkie klasy dziedzicz¹ce po TaskBase<T>
        var handlerClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateHandlerClass(node),
                transform: static (ctx, _) => GetHandlerInfo(ctx))
            .Where(static info => info is not null);

        // Zbierz wszystkie handlery i wygeneruj kod
        var compilation = context.CompilationProvider.Combine(handlerClasses.Collect());

        context.RegisterSourceOutput(compilation, static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsCandidateHandlerClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl
               && classDecl.BaseList is not null
               && classDecl.BaseList.Types.Any();
    }

    private static TaskHandlerInfo? GetHandlerInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);

        if (symbol is not INamedTypeSymbol classSymbol)
            return null;

        // SprawdŸ czy klasa jest abstract lub static
        if (classSymbol.IsAbstract || classSymbol.IsStatic)
            return null;

        // ZnajdŸ klasê bazow¹ TaskBase<T>
        var baseType = classSymbol.BaseType;
        while (baseType != null)
        {
            if (baseType.IsGenericType 
                && baseType.Name == TaskBaseClassName
                && baseType.ContainingNamespace?.ToDisplayString() == TaskBaseNamespace
                && baseType.TypeArguments.Length == 1)
            {
                var taskType = baseType.TypeArguments[0];
                
                return new TaskHandlerInfo(
                    HandlerFullName: classSymbol.ToDisplayString(),
                    HandlerName: classSymbol.Name,
                    TaskFullName: taskType.ToDisplayString(),
                    TaskName: taskType.Name,
                    Namespace: classSymbol.ContainingNamespace?.ToDisplayString() ?? "Global"
                );
            }
            baseType = baseType.BaseType;
        }

        return null;
    }

    private static void Execute(Compilation compilation, ImmutableArray<TaskHandlerInfo?> handlers, SourceProductionContext context)
    {
        var validHandlers = handlers
            .Where(h => h is not null)
            .Cast<TaskHandlerInfo>()
            .Distinct()
            .ToList();

        if (validHandlers.Count == 0)
            return;

        // Generuj extension method dla rejestracji
        var registrationSource = GenerateRegistrationExtensions(validHandlers);
        context.AddSource("TaskHandlerRegistration.g.cs", registrationSource);
    }

    private static string GenerateRegistrationExtensions(List<TaskHandlerInfo> handlers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Zonit.Services.EventMessage;");
        sb.AppendLine();

        // Dodaj using dla ka¿dego namespace handlera
        var namespaces = handlers.Select(h => h.Namespace).Distinct().OrderBy(n => n);
        foreach (var ns in namespaces)
        {
            if (ns != "Zonit.Services.EventMessage" && ns != "Global")
            {
                sb.AppendLine($"using {ns};");
            }
        }

        sb.AppendLine();
        sb.AppendLine("namespace Zonit.Messaging.Tasks;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated extension methods for registering all task handlers.");
        sb.AppendLine("/// This class is generated by TaskHandlerGenerator.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class GeneratedTaskHandlerExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers all discovered task handlers (TaskBase&lt;T&gt;) in the DI container.");
        sb.AppendLine("    /// This method is AOT/Trimming safe - no reflection at runtime.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IServiceCollection AddTaskHandlers(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var handler in handlers)
        {
            sb.AppendLine($"        // Handler: {handler.HandlerName} for task: {handler.TaskName}");
            sb.AppendLine($"        services.AddScoped<ITaskHandler, {handler.HandlerFullName}>();");
            sb.AppendLine($"        services.AddScoped<{handler.HandlerFullName}>();");
        }

        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the list of all discovered task handler types for AOT-safe subscription.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static System.Type[] GetTaskHandlerTypes()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new System.Type[]");
        sb.AppendLine("        {");

        foreach (var handler in handlers)
        {
            sb.AppendLine($"            typeof({handler.HandlerFullName}),");
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private record TaskHandlerInfo(
        string HandlerFullName,
        string HandlerName,
        string TaskFullName,
        string TaskName,
        string Namespace
    );
}
