using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Zonit.Messaging.Tasks.SourceGenerators;

/// <summary>
/// Source generator that emits AOT/trimming-safe task-handler registration.
/// Scans the project for classes deriving from TaskHandler&lt;T&gt; and emits a
/// reflection-free registration applied via a ModuleInitializer + TaskSegmentRegistry.
/// </summary>
[Generator]
public class TaskHandlerGenerator : IIncrementalGenerator
{
    private const string TaskHandlerClassName = "TaskHandler";
    private const string TaskHandlerNamespace = "Zonit.Messaging.Tasks";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes deriving from TaskHandler<T>
        var handlerClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateHandlerClass(node),
                transform: static (ctx, _) => GetHandlerInfo(ctx))
            .Where(static info => info is not null);

        // Zbierz wszystkie handlery i wygeneruj kod
        var compilation = context.CompilationProvider.Combine(handlerClasses.Collect());

        context.RegisterSourceOutput(compilation, static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsCandidateHandlerClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl
               && classDecl.BaseList is not null
               && classDecl.BaseList.Types.Any();
    }

    private static TaskHandlerInfo? GetHandlerInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);

        if (symbol is not INamedTypeSymbol classSymbol)
            return null;

        // Skip abstract/static classes
        if (classSymbol.IsAbstract || classSymbol.IsStatic)
            return null;

        // Skip open generic handler classes (e.g. MyHandler<T>): a closed type argument
        // is required to emit a concrete, AOT-safe registration.
        if (classSymbol.IsGenericType && classSymbol.TypeParameters.Length > 0)
            return null;

        // Walk the base chain for TaskHandler<TTask>.
        var baseType = classSymbol.BaseType;
        while (baseType != null)
        {
            if (baseType.IsGenericType
                && baseType.TypeArguments.Length == 1
                && baseType.Name == TaskHandlerClassName
                && baseType.ContainingNamespace?.ToDisplayString() == TaskHandlerNamespace)
            {
                var taskType = baseType.TypeArguments[0];

                // Skip if the task type is still an unbound type parameter.
                if (taskType is ITypeParameterSymbol)
                    return null;

                return new TaskHandlerInfo(
                    HandlerFullName: classSymbol.ToDisplayString(),
                    HandlerName: classSymbol.Name,
                    TaskFullName: taskType.ToDisplayString(),
                    TaskName: taskType.Name,
                    Namespace: classSymbol.ContainingNamespace?.ToDisplayString() ?? "Global"
                );
            }
            baseType = baseType.BaseType;
        }

        return null;
    }

    private static void Execute(Compilation compilation, ImmutableArray<TaskHandlerInfo?> handlers, SourceProductionContext context)
    {
        var validHandlers = handlers
            .Where(h => h is not null)
            .Cast<TaskHandlerInfo>()
            .Distinct()
            .ToList();

        if (validHandlers.Count == 0)
            return;

        var assemblyName = compilation.AssemblyName ?? "Unknown";
        var safeAssemblyName = assemblyName.Replace(".", "_").Replace("-", "_");

        var source = GenerateRegistration(validHandlers, safeAssemblyName);
        context.AddSource("TaskHandlerRegistration.g.cs", source);
    }

    private static string GenerateRegistration(List<TaskHandlerInfo> handlers, string safeAssemblyName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Zonit.Messaging.Tasks;");
        sb.AppendLine("using Zonit.Messaging.Tasks.Hosting;");
        sb.AppendLine();
        sb.AppendLine("namespace Zonit.Messaging.Tasks.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated task handler registrations.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"internal static class TaskHandlerRegistrations_{safeAssemblyName}");
        sb.AppendLine("{");
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        TaskSegmentRegistry.Register(RegisterServices);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    internal static void RegisterServices(IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var handler in handlers)
        {
            sb.AppendLine($"        // Handler: {handler.HandlerName} for task: {handler.TaskName}");
            sb.AppendLine($"        services.TryAddScoped<{handler.HandlerFullName}>();");
            // Multiple handlers can exist per task type - use TryAddEnumerable with concrete impl type
            // so GetServices<ITaskHandler<T>>() returns all of them.
            sb.AppendLine($"        services.TryAddEnumerable(ServiceDescriptor.Scoped<ITaskHandler<{handler.TaskFullName}>, {handler.HandlerFullName}>(static sp => sp.GetRequiredService<{handler.HandlerFullName}>()));");
            sb.AppendLine($"        services.TryAddEnumerable(ServiceDescriptor.Singleton<TaskHandlerRegistration>(new TaskHandlerRegistration<{handler.TaskFullName}>()));");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private record TaskHandlerInfo(
        string HandlerFullName,
        string HandlerName,
        string TaskFullName,
        string TaskName,
        string Namespace
    );
}
