using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Zonit.Messaging.Tasks.SourceGenerators;

/// <summary>
/// Source Generator kt�ry automatycznie generuje rejestracj� handler�w zada� dla AOT/Trimming.
/// Skanuje projekt w poszukiwaniu klas dziedzicz�cych po TaskHandler&lt;T&gt; lub TaskBase&lt;T&gt; i generuje:
/// 1. Extension method AddTaskHandlers() dla automatycznej rejestracji wszystkich handler�w
/// 2. AOT-safe subscription bez reflection
/// </summary>
[Generator]
public class TaskHandlerGenerator : IIncrementalGenerator
{
    // New API
    private const string TaskHandlerClassName = "TaskHandler";
    private const string TaskHandlerNamespace = "Zonit.Messaging.Tasks";

    // Legacy API
    private const string TaskBaseClassName = "TaskBase";
    private const string TaskBaseNamespace = "Zonit.Services.EventMessage";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Znajd� wszystkie klasy dziedzicz�ce po TaskBase<T>
        var handlerClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateHandlerClass(node),
                transform: static (ctx, _) => GetHandlerInfo(ctx))
            .Where(static info => info is not null);

        // Zbierz wszystkie handlery i wygeneruj kod
        var compilation = context.CompilationProvider.Combine(handlerClasses.Collect());

        context.RegisterSourceOutput(compilation, static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsCandidateHandlerClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl
               && classDecl.BaseList is not null
               && classDecl.BaseList.Types.Any();
    }

    private static TaskHandlerInfo? GetHandlerInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);

        if (symbol is not INamedTypeSymbol classSymbol)
            return null;

        // Sprawd� czy klasa jest abstract lub static
        if (classSymbol.IsAbstract || classSymbol.IsStatic)
            return null;

        // Znajd� klas� bazow� TaskHandler<T> (new API) lub TaskBase<T> (legacy)
        var baseType = classSymbol.BaseType;
        while (baseType != null)
        {
            if (baseType.IsGenericType && baseType.TypeArguments.Length == 1)
            {
                var baseTypeName = baseType.Name;
                var baseTypeNamespace = baseType.ContainingNamespace?.ToDisplayString();

                // Check for new TaskHandler<T> API
                bool isNewApi = baseTypeName == TaskHandlerClassName
                    && baseTypeNamespace == TaskHandlerNamespace;

                // Check for legacy TaskBase<T> API
                bool isLegacyApi = baseTypeName == TaskBaseClassName
                    && baseTypeNamespace == TaskBaseNamespace;

                if (isNewApi || isLegacyApi)
                {
                    var taskType = baseType.TypeArguments[0];

                    return new TaskHandlerInfo(
                        HandlerFullName: classSymbol.ToDisplayString(),
                        HandlerName: classSymbol.Name,
                        TaskFullName: taskType.ToDisplayString(),
                        TaskName: taskType.Name,
                        Namespace: classSymbol.ContainingNamespace?.ToDisplayString() ?? "Global",
                        IsLegacy: isLegacyApi
                    );
                }
            }
            baseType = baseType.BaseType;
        }

        return null;
    }

    private static void Execute(Compilation compilation, ImmutableArray<TaskHandlerInfo?> handlers, SourceProductionContext context)
    {
        var validHandlers = handlers
            .Where(h => h is not null)
            .Cast<TaskHandlerInfo>()
            .Distinct()
            .ToList();

        if (validHandlers.Count == 0)
            return;

        var assemblyName = compilation.AssemblyName ?? "Unknown";
        var safeAssemblyName = assemblyName.Replace(".", "_").Replace("-", "_");

        var source = GenerateRegistration(validHandlers, safeAssemblyName);
        context.AddSource("TaskHandlerRegistration.g.cs", source);
    }

    private static string GenerateRegistration(List<TaskHandlerInfo> handlers, string safeAssemblyName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Zonit.Messaging.Tasks;");
        sb.AppendLine("using Zonit.Messaging.Tasks.Hosting;");

        if (handlers.Any(h => h.IsLegacy))
        {
            sb.AppendLine("using Zonit.Services.EventMessage;");
        }
        sb.AppendLine();
        sb.AppendLine("namespace Zonit.Messaging.Tasks.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated task handler registrations.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"internal static class TaskHandlerRegistrations_{safeAssemblyName}");
        sb.AppendLine("{");
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        TaskSegmentRegistry.Register(RegisterServices);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    internal static void RegisterServices(IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var handler in handlers)
        {
            sb.AppendLine($"        // Handler: {handler.HandlerName} for task: {handler.TaskName}{(handler.IsLegacy ? " [LEGACY]" : "")}");
            sb.AppendLine($"        services.TryAddScoped<{handler.HandlerFullName}>();");
            // Multiple handlers can exist per task type - use TryAddEnumerable with concrete impl type
            // so GetServices<ITaskHandler<T>>() returns all of them.
            sb.AppendLine($"        services.TryAddEnumerable(ServiceDescriptor.Scoped<ITaskHandler<{handler.TaskFullName}>, {handler.HandlerFullName}>(static sp => sp.GetRequiredService<{handler.HandlerFullName}>()));");
            sb.AppendLine($"        services.TryAddEnumerable(ServiceDescriptor.Singleton<TaskHandlerRegistration>(new TaskHandlerRegistration<{handler.TaskFullName}>()));");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private record TaskHandlerInfo(
        string HandlerFullName,
        string HandlerName,
        string TaskFullName,
        string TaskName,
        string Namespace,
        bool IsLegacy
    );
}
