using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Zonit.Messaging.Schedules.SourceGenerators;

/// <summary>
/// Source generator that emits AOT/trimming-safe schedule-handler registration.
/// Scans the project for classes implementing IScheduleHandler&lt;T&gt; and emits a
/// reflection-free registration applied via a ModuleInitializer + ScheduleSegmentRegistry,
/// surfaced through AddScheduleServices()/AddScheduleHandlers().
/// </summary>
[Generator]
public class ScheduleHandlerGenerator : IIncrementalGenerator
{
    private const string ScheduleHandlerInterfaceName = "IScheduleHandler";
    private const string ScheduleHandlerNamespace = "Zonit.Messaging.Schedules";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes implementing IScheduleHandler<T>
        var handlerClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateHandlerClass(node),
                transform: static (ctx, _) => GetHandlerInfo(ctx))
            .Where(static info => info is not null);

        // Collect all handlers and generate code
        var compilation = context.CompilationProvider.Combine(handlerClasses.Collect());

        context.RegisterSourceOutput(compilation, static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsCandidateHandlerClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl
               && classDecl.BaseList is not null
               && classDecl.BaseList.Types.Any();
    }

    private static ScheduleHandlerInfo? GetHandlerInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);

        if (symbol is not INamedTypeSymbol classSymbol)
            return null;

        // Check if class is abstract or static
        if (classSymbol.IsAbstract || classSymbol.IsStatic)
            return null;

        // Skip open generic types (classes with unbound type parameters like MyClass<T>)
        if (classSymbol.IsGenericType && classSymbol.TypeParameters.Length > 0)
            return null;

        // Find interface IScheduleHandler<T>
        foreach (var iface in classSymbol.AllInterfaces)
        {
            if (iface.IsGenericType &&
                iface.TypeArguments.Length == 1 &&
                iface.Name == ScheduleHandlerInterfaceName &&
                iface.ContainingNamespace?.ToDisplayString() == ScheduleHandlerNamespace)
            {
                var dataType = iface.TypeArguments[0];

                // Skip if data type is a type parameter (unbound generic)
                if (dataType is ITypeParameterSymbol)
                    return null;

                return new ScheduleHandlerInfo(
                    HandlerFullName: classSymbol.ToDisplayString(),
                    HandlerName: classSymbol.Name,
                    DataTypeFullName: dataType.ToDisplayString(),
                    DataTypeName: dataType.Name,
                    Namespace: classSymbol.ContainingNamespace?.ToDisplayString() ?? "Global"
                );
            }
        }

        return null;
    }

    private static void Execute(Compilation compilation, ImmutableArray<ScheduleHandlerInfo?> handlers, SourceProductionContext context)
    {
        var validHandlers = handlers
            .Where(h => h is not null)
            .Cast<ScheduleHandlerInfo>()
            .Distinct()
            .ToList();

        if (validHandlers.Count == 0)
            return;

        var assemblyName = compilation.AssemblyName ?? "Unknown";
        var safeAssemblyName = assemblyName.Replace(".", "_").Replace("-", "_");

        var source = GenerateRegistration(validHandlers, safeAssemblyName);
        context.AddSource("ScheduleHandlerRegistration.g.cs", source);
    }

    private static string GenerateRegistration(List<ScheduleHandlerInfo> handlers, string safeAssemblyName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Zonit.Messaging.Schedules;");
        sb.AppendLine();
        sb.AppendLine("namespace Zonit.Messaging.Schedules.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated schedule handler registrations.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"internal static class ScheduleHandlerRegistrations_{safeAssemblyName}");
        sb.AppendLine("{");
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        ScheduleSegmentRegistry.Register(RegisterServices);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    internal static void RegisterServices(IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var handler in handlers)
        {
            sb.AppendLine($"        // Handler: {handler.HandlerName} for data: {handler.DataTypeName}");
            sb.AppendLine($"        services.TryAddScoped<{handler.HandlerFullName}>();");
            // Use the two-arg generic overload so the factory delegate's runtime type is
            // Func<IServiceProvider, THandler> (not Func<IServiceProvider, IScheduleHandler<T>>),
            // which makes ServiceDescriptor.GetImplementationType() return the concrete handler type.
            // This is required by TryAddEnumerable, which rejects descriptors where the implementation
            // type equals the service type (or is object).
            sb.AppendLine($"        services.TryAddEnumerable(ServiceDescriptor.Scoped<IScheduleHandler<{handler.DataTypeFullName}>, {handler.HandlerFullName}>(static sp => sp.GetRequiredService<{handler.HandlerFullName}>()));");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private record ScheduleHandlerInfo(
        string HandlerFullName,
        string HandlerName,
        string DataTypeFullName,
        string DataTypeName,
        string Namespace
    );
}
