using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Zonit.Messaging.Commands.SourceGenerators;

/// <summary>
/// Source Generator that automatically generates AOT-safe command handler registration.
/// Scans the project for classes implementing IRequestHandler and generates:
/// 1. An ICommandProviderSegment implementation for AOT-safe dispatch
/// 2. Registration code that adds the segment to DI
/// </summary>
[Generator]
public class CommandHandlerGenerator : IIncrementalGenerator
{
    private const string RequestHandlerInterfaceName = "IRequestHandler";
    private const string RequestHandlerNamespace = "Zonit.Messaging.Commands";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidateHandlerClass(node),
                transform: static (ctx, _) => GetHandlerInfo(ctx))
            .Where(static info => info is not null);

        var compilation = context.CompilationProvider.Combine(handlerClasses.Collect());
        context.RegisterSourceOutput(compilation, static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsCandidateHandlerClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl
               && classDecl.BaseList is not null
               && classDecl.BaseList.Types.Any();
    }

    private static HandlerInfo? GetHandlerInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);

        if (symbol is not INamedTypeSymbol classSymbol)
            return null;

        if (classSymbol.IsAbstract || classSymbol.IsStatic)
            return null;

        // Skip open generic handler classes (e.g. MyHandler<T>): a closed type argument
        // is required to emit a concrete, AOT-safe registration.
        if (classSymbol.IsGenericType && classSymbol.TypeParameters.Length > 0)
            return null;

        var handlerInterface = classSymbol.AllInterfaces
            .FirstOrDefault(i => i.IsGenericType
                && i.Name == RequestHandlerInterfaceName
                && i.TypeArguments.Length == 2
                && i.ContainingNamespace?.ToDisplayString() == RequestHandlerNamespace);

        if (handlerInterface is null)
            return null;

        var requestType = handlerInterface.TypeArguments[0];
        var responseType = handlerInterface.TypeArguments[1];

        // Skip if request/response are still unbound type parameters.
        if (requestType is ITypeParameterSymbol || responseType is ITypeParameterSymbol)
            return null;

        return new HandlerInfo(
            HandlerFullName: classSymbol.ToDisplayString(),
            HandlerName: classSymbol.Name,
            RequestFullName: requestType.ToDisplayString(),
            RequestName: requestType.Name,
            ResponseFullName: responseType.ToDisplayString(),
            ResponseName: responseType.Name,
            Namespace: classSymbol.ContainingNamespace?.ToDisplayString() ?? "Global"
        );
    }

    private static void Execute(Compilation compilation, ImmutableArray<HandlerInfo?> handlers, SourceProductionContext context)
    {
        var validHandlers = handlers
            .Where(h => h is not null)
            .Cast<HandlerInfo>()
            .Distinct()
            .ToList();

        if (validHandlers.Count == 0)
            return;

        var assemblyName = compilation.AssemblyName ?? "Unknown";
        var safeAssemblyName = assemblyName.Replace(".", "_").Replace("-", "_");

        // Generate the segment and registration
        var source = GenerateSegmentAndRegistration(validHandlers, safeAssemblyName);
        context.AddSource("CommandHandlerSegment.g.cs", source);
    }

    private static string GenerateSegmentAndRegistration(List<HandlerInfo> handlers, string safeAssemblyName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Zonit.Messaging.Commands;");
        sb.AppendLine();
        sb.AppendLine("namespace Zonit.Messaging.Commands.Generated;");
        sb.AppendLine();
        
        // Generate the segment class
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// AOT-safe command provider segment for this assembly.");
        sb.AppendLine("/// Handles command dispatch without reflection.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"internal sealed class CommandProviderSegment_{safeAssemblyName} : ICommandProviderSegment");
        sb.AppendLine("{");
        sb.AppendLine("    public Task<(bool Handled, TResponse? Result)> TryHandleAsync<TResponse>(");
        sb.AppendLine("        IRequest<TResponse> request,");
        sb.AppendLine("        IServiceProvider serviceProvider,");
        sb.AppendLine("        CancellationToken cancellationToken)");
        sb.AppendLine("        where TResponse : notnull");
        sb.AppendLine("    {");
        sb.AppendLine("        return request switch");
        sb.AppendLine("        {");

        foreach (var handler in handlers)
        {
            sb.AppendLine($"            {handler.RequestFullName} r => HandleAsync<{handler.RequestFullName}, {handler.ResponseFullName}, TResponse>(r, serviceProvider, cancellationToken),");
        }

        sb.AppendLine("            _ => Task.FromResult<(bool, TResponse?)>((false, default))");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static async Task<(bool Handled, TResponse? Result)> HandleAsync<TRequest, THandlerResponse, TResponse>(");
        sb.AppendLine("        TRequest request,");
        sb.AppendLine("        IServiceProvider serviceProvider,");
        sb.AppendLine("        CancellationToken cancellationToken)");
        sb.AppendLine("        where TRequest : IRequest<THandlerResponse>");
        sb.AppendLine("        where THandlerResponse : notnull");
        sb.AppendLine("        where TResponse : notnull");
        sb.AppendLine("    {");
        sb.AppendLine("        var handler = serviceProvider.GetRequiredService<IRequestHandler<TRequest, THandlerResponse>>();");
        sb.AppendLine("        var result = await handler.HandleAsync(request, cancellationToken);");
        sb.AppendLine("        return (true, (TResponse?)(object?)result);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // Generate the registration class with ModuleInitializer
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated registration for command handlers.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"internal static class CommandHandlerRegistrations_{safeAssemblyName}");
        sb.AppendLine("{");
        sb.AppendLine("    [System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        // Register handlers when assembly loads");
        sb.AppendLine("        CommandSegmentRegistry.Register(RegisterServices);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    internal static void RegisterServices(IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        // Register the segment using TryAddEnumerable to prevent duplicates");
        sb.AppendLine($"        services.TryAddEnumerable(ServiceDescriptor.Singleton<ICommandProviderSegment, CommandProviderSegment_{safeAssemblyName}>());");
        sb.AppendLine();

        foreach (var handler in handlers)
        {
            sb.AppendLine($"        // Handler: {handler.HandlerName}");
            sb.AppendLine($"        services.TryAddScoped<{handler.HandlerFullName}>();");
            sb.AppendLine($"        services.TryAddScoped<IRequestHandler<{handler.RequestFullName}, {handler.ResponseFullName}>>(sp => sp.GetRequiredService<{handler.HandlerFullName}>());");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private record HandlerInfo(
        string HandlerFullName,
        string HandlerName,
        string RequestFullName,
        string RequestName,
        string ResponseFullName,
        string ResponseName,
        string Namespace
    );
}
