name: Bump AssemblyVersion

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Which part of the version do you conquer?'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure xmllint is installed
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Bump ${ { github.event.inputs.bump } } version in Directory.Packages.props
        id: bump
        run: |
          props_file="Source/Directory.Packages.props"
          # Pobierz aktualn¹ wersjê
          current_version=$(xmllint --xpath "string(//AssemblyVersion)" $props_file)
          echo "Obecna wersja: $current_version"

          IFS='.' read -r major minor patch <<< "$current_version"

          bump="${{ github.event.inputs.bump }}"
          if [ "$bump" = "major" ]; then
            major=$((major+1))
            minor=0
            patch=0
          elif [ "$bump" = "minor" ]; then
            minor=$((minor+1))
            patch=0
          else
            patch=$((patch+1))
          fi
          new_version="$major.$minor.$patch"
          echo "Ustawiam now¹ wersjê: $new_version"
          # Zamieniam wersjê w pliku
          sed -i "s/<AssemblyVersion>$current_version<\/AssemblyVersion>/<AssemblyVersion>$new_version<\/AssemblyVersion>/" $props_file
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Commit and push new version
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add Source/Directory.Packages.props
          git commit -m "Bump ${ { github.event.inputs.bump } } version to ${{ steps.bump.outputs.new_version }} [ci skip]" || echo "Nothing to commit"
          git push origin HEAD:main