name: Check NuGet Package Versions and Trigger Publish

on:
  workflow_dispatch:
  push:
    paths:
      - 'Source/Directory.Packages.props'

jobs:
  check-and-publish:
    uses: Zonit/.github/.github/workflows/reusable-check-nuget-and-publish.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}